memory_limit = 4G
max_execution_time = 1800
realpath_cache_size = 10M
realpath_cache_ttl = 7200
upload_max_filesize = 64M
post_max_size = 64M
zlib.output_compression = On
date.timezone = UTC

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 512
opcache.max_accelerated_files = 100000
opcache.validate_timestamps = 1
opcache.save_comments = 1
